"use client";

/**
 * P1-08 — Ask, the contextual assistant.
 *
 * The reply is produced by a background job, not by the request that posts the
 * question, so the answer arrives a moment later. The screen polls for it with
 * a clear working state and a bounded wait: if nothing arrives it says the
 * answer is still being prepared and the question was saved, which is true,
 * rather than claiming none is coming.
 *
 * The assistant may propose a change to the farmer's records. It never applies
 * one. A proposal is fetched and shown in full — what changes, on which record,
 * and to what value — and only an explicit Confirm sends it. That is the whole
 * safety property of this screen: nothing is approved unseen.
 */
import { AppShell } from "@/components/app-shell";
import { useLanguage } from "@/components/language-provider";
import { Button, Callout, Card, ErrorState, Skeleton, TextField } from "@/components/ui";
import { useAuth } from "@/features/auth/auth-provider";
import { useActiveField } from "@/features/fields/active-field";
import { newIdempotencyKey } from "@/lib/api/client";
import type { Conversation, Field, Message } from "@/lib/api/contract";
import { ApiError } from "@/lib/api/envelope";
import { useApiQuery } from "@/lib/api/query";
import {
  conversations as conversationsApi,
  fields as fieldsApi,
} from "@/lib/api/routes";
import { formatTime } from "@/lib/format";
import { cn } from "@/lib/utils";
import { ProposalCard } from "@/features/ask/proposal-card";
import { VoiceRecorder } from "@/features/ask/voice-recorder";
import { uploadAttachment, UploadError, ACCEPTED_IMAGE_TYPES } from "@/lib/media/upload";
import { BookOpen, ImagePlus, Mic, Send, Sprout, X } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";

/**
 * The reply is generated by a background job. Work starts as soon as the
 * message is queued, so it usually lands in a few seconds, but a cold worker or
 * a slow model can take longer. Waiting ~45s covers that without stranding a
 * farmer in front of a spinner.
 */
const REPLY_POLL_ATTEMPTS = 22;
const REPLY_POLL_INTERVAL_MS = 2000;

export function AskScreen() {
  const { t, language } = useLanguage();
  const { user } = useAuth();
  const uid = user?.uid ?? null;

  const fieldsQuery = useApiQuery(
    [uid, "fields"],
    (signal) => fieldsApi.list({ signal, limit: 50 }),
    { enabled: Boolean(uid) },
  );
  const visible = (fieldsQuery.data?.items ?? []).filter((f) => !f.archived);
  const { activeId } = useActiveField(
    uid,
    visible.map((f) => f.id),
  );
  const activeField = visible.find((f) => f.id === activeId) ?? null;

  const [conversation, setConversation] = useState<Conversation | null>(null);
  const [photo, setPhoto] = useState<{ file: File; preview: string } | null>(null);
  const [uploading, setUploading] = useState(false);
  const fileInput = useRef<HTMLInputElement | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [draft, setDraft] = useState("");
  const [sending, setSending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  /** Set once we have waited for a reply and none arrived. */
  const [replyUnavailable, setReplyUnavailable] = useState(false);

  const threadRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    threadRef.current?.scrollTo({ top: threadRef.current.scrollHeight });
  }, [messages.length, replyUnavailable]);

  /** Creates the conversation on first send, scoped to the active field and
   *  the farmer's chosen language so the server knows both. */
  const ensureConversation = useCallback(async (): Promise<Conversation> => {
    if (conversation) return conversation;
    const { data } = await conversationsApi.create(
      {
        field_id: activeField?.id ?? null,
        season_id: null,
        language,
      },
      newIdempotencyKey(),
    );
    setConversation(data);
    return data;
  }, [conversation, activeField, language]);

  /** After a confirmed proposal the records changed, so re-read the thread. */
  const refreshThread = useCallback(() => {
    if (!conversation) return;
    conversationsApi
      .messages(conversation.id, { limit: 100 })
      .then(({ data }) => setMessages(data.items ?? []))
      .catch(() => {
        /* The confirmation already succeeded; a failed refresh is not worth an error. */
      });
  }, [conversation]);

  async function send() {
    const text = draft.trim();
    if (text === "" || sending) return;

    setSending(true);
    setError(null);
    setReplyUnavailable(false);

    try {
      const convo = await ensureConversation();
      // Upload first: attaching an id that does not exist yet would be refused.
      let mediaIds: string[] = [];
      if (photo) {
        setUploading(true);
        try {
          mediaIds = [await uploadAttachment(photo.file, newIdempotencyKey())];
        } finally {
          setUploading(false);
        }
      }
      const { data: sent } = await postMessage(convo.id, text, mediaIds);
      if (photo) {
        if (photo.preview) URL.revokeObjectURL(photo.preview);
        setPhoto(null);
      }
      setMessages((prev) => [...prev, sent]);
      setDraft("");

      // The reply comes from a background job, so wait for a new assistant turn
      // rather than any assistant turn: earlier answers are already on screen.
      const before = messages.filter((m) => m.role === "assistant").length;
      let found = false;
      for (let attempt = 0; attempt < REPLY_POLL_ATTEMPTS; attempt += 1) {
        await new Promise((resolve) => setTimeout(resolve, REPLY_POLL_INTERVAL_MS));
        const { data: page } = await conversationsApi.messages(convo.id, { limit: 100 });
        const items = page.items ?? [];
        setMessages(items);
        if (items.filter((m) => m.role === "assistant").length > before) {
          found = true;
          break;
        }
      }
      if (!found) setReplyUnavailable(true);
    } catch (cause) {
      setError(
        cause instanceof ApiError
          ? cause.isDependencyUnavailable
            ? "The assistant service is unavailable right now. Your question was not sent."
            : cause.message
          : cause instanceof UploadError
            ? cause.message
            : t("errorUnreachable"),
      );
    } finally {
      setSending(false);
    }
  }

  if (fieldsQuery.isLoading) {
    return (
      <AppShell title={t("navAsk")}>
        <div className="space-y-3" aria-busy="true">
          <Skeleton className="h-20 w-full rounded-card" />
          <Skeleton className="h-40 w-full rounded-card" />
        </div>
      </AppShell>
    );
  }

  if (fieldsQuery.error) {
    return (
      <AppShell title={t("navAsk")}>
        <ErrorState
          title={t("errorTitle")}
          message={fieldsQuery.error.message}
          retryLabel={t("retry")}
          onRetry={fieldsQuery.error.retryable ? fieldsQuery.refetch : undefined}
        />
      </AppShell>
    );
  }

  return (
    <AppShell title={t("navAsk")}>
      <div className="flex flex-col gap-4">
        <ContextStrip field={activeField} />

        <Card className="flex min-h-[18rem] flex-col p-0">
          <div ref={threadRef} className="flex-1 space-y-3 overflow-y-auto p-4">
            {messages.length === 0 && !sending ? (
              <Opening />
            ) : (
              messages.map((message) => (
                <Bubble key={message.id} message={message} onApplied={refreshThread} />
              ))
            )}

            {sending ? (
              <p className="text-center text-sm text-slate" aria-live="polite">
                Sending your question…
              </p>
            ) : null}

            {replyUnavailable ? <NoAnswerAvailable /> : null}
          </div>

          <form
            className="flex items-end gap-2 border-t border-mist p-3"
            onSubmit={(e) => {
              e.preventDefault();
              void send();
            }}
          >
            <TextField
              label="Your question"
              className="flex-1"
              value={draft}
              onChange={(e) => setDraft(e.target.value)}
              placeholder="Ask about your field"
              disabled={sending}
            />
            <input
              ref={fileInput}
              type="file"
              accept={ACCEPTED_IMAGE_TYPES.join(",")}
              className="sr-only"
              onChange={(e) => {
                const file = e.target.files?.[0];
                if (!file) return;
                if (photo) URL.revokeObjectURL(photo.preview);
                setPhoto({ file, preview: URL.createObjectURL(file) });
                e.target.value = "";
              }}
            />
            <Button
              type="button"
              variant="secondary"
              size="lg"
              onClick={() => fileInput.current?.click()}
              disabled={sending}
              aria-label="Attach a photo"
            >
              <ImagePlus aria-hidden className="size-4" />
            </Button>
            <VoiceRecorder
              disabled={sending}
              onError={setError}
              onRecorded={(file) => {
                if (photo) URL.revokeObjectURL(photo.preview);
                setPhoto({ file, preview: "" });
              }}
            />
            <Button type="submit" size="lg" busy={sending} disabled={draft.trim() === "" && !photo}>
              <Send aria-hidden className="size-4" />
              Send
            </Button>
          </form>
        </Card>

        {error ? (
          <Callout tone="blocked" title={t("errorTitle")}>
            {error}
          </Callout>
        ) : null}

        {photo ? (
          <Card className="flex items-center gap-3 p-3">
            {photo.preview ? (
              /* eslint-disable-next-line @next/next/no-img-element -- object URL, not a remote asset */
              <img
                src={photo.preview}
                alt="Photo you are about to attach"
                className="size-14 shrink-0 rounded-control object-cover"
              />
            ) : (
              <span className="grid size-14 shrink-0 place-items-center rounded-control bg-forest/10 text-forest">
                <Mic aria-hidden className="size-5" />
              </span>
            )}
            <div className="min-w-0 flex-1">
              <p className="truncate text-sm font-medium text-ink">{photo.file.name}</p>
              <p className="text-xs text-slate">
                {uploading
                  ? "Uploading…"
                  : photo.preview
                    ? "Attached to your next question"
                    : "Voice note ready — press Send"}
              </p>
            </div>
            <Button
              type="button"
              variant="secondary"
              onClick={() => {
                URL.revokeObjectURL(photo.preview);
                setPhoto(null);
              }}
              disabled={sending}
              aria-label="Remove the photo"
            >
              <X aria-hidden className="size-4" />
            </Button>
          </Card>
        ) : null}

        {/* Voice input still needs a recorder and a transcription step, so it is
            named rather than offered: a microphone that discards what a farmer
            said is worse than no microphone. */}
        <Callout tone="info" className="text-xs">
          You can attach a photo or ask by voice in any of the languages above. A voice note is
          sent as you recorded it; nothing is transcribed on this device.
        </Callout>
      </div>
    </AppShell>
  );
}

/** Posted separately so `send()` reads linearly. */
async function postMessage(conversationId: string, text: string, mediaIds: string[] = []) {
  return conversationsApi.postMessage(
    conversationId,
    mediaIds.length ? { text, media_ids: mediaIds } : { text },
    newIdempotencyKey(),
  );
}

function ContextStrip({ field }: { field: Field | null }) {
  return (
    <Card className="p-3 text-sm">
      <p className="text-xs font-semibold uppercase tracking-wide text-slate">
        What the assistant can see
      </p>
      {field ? (
        <p className="mt-1 text-ink">
          <span className="font-semibold">{field.name}</span> — your own field records only.
        </p>
      ) : (
        <p className="mt-1 text-slate">
          No field selected yet, so there is no field context to answer from.
        </p>
      )}
      <p className="mt-1 text-xs text-slate">
        It can only read your own records. It cannot see other farmers.
      </p>
    </Card>
  );
}

function Opening() {
  return (
    <div className="py-6 text-center">
      <p className="text-h3 font-semibold">Ask about your field</p>
      <p className="mx-auto mt-1.5 max-w-[36ch] text-sm text-slate">
        Questions about your own crop, water, spending or season records — in your own language.
      </p>
    </div>
  );
}

function Bubble({ message, onApplied }: { message: Message; onApplied?: () => void }) {
  const mine = message.role === "user";
  return (
    <div className={cn("flex flex-col", mine ? "items-end" : "items-start")}>
      <div
        className={cn(
          "max-w-[85%] rounded-card px-3 py-2 text-sm",
          mine ? "bg-forest text-white" : "border border-mist bg-card text-ink",
        )}
      >
        <p className="whitespace-pre-wrap break-words">{message.text ?? ""}</p>
        <p className={cn("mt-1 text-xs", mine ? "text-white/70" : "text-slate")}>
          {formatTime(message.created_at)}
        </p>

        {/* Citations. The spec requires an answer's facts to link back to the
            record they came from. Only ids are returned, so they are listed
            rather than resolved — see IR-009. */}
        {message.source_record_ids && message.source_record_ids.length > 0 ? (
          <p className="mt-1 text-xs opacity-80">
            Based on {message.source_record_ids.length} of your records
          </p>
        ) : null}

      </div>

      {/* The proposal is rendered outside the bubble and at full width, because
          it is a decision the farmer has to make rather than part of the reply. */}
      {!mine && message.proposal_ids && message.proposal_ids.length > 0 ? (
        <div className="mt-2 w-full max-w-[85%] space-y-2">
          {message.proposal_ids.map((id) => (
            <ProposalCard key={id} proposalId={id} onApplied={onApplied} />
          ))}
        </div>
      ) : null}
    </div>
  );
}

/**
 * Shown when the wait elapsed without a new assistant turn.
 *
 * The question is genuinely saved and the job genuinely still queued, so this
 * says the answer is still being prepared rather than that none is coming. It
 * offers the deterministic routes meanwhile instead of inviting a blind retry,
 * which would only queue a second question.
 */
function NoAnswerAvailable() {
  return (
    <Callout tone="caution" title="Still preparing an answer">
      <p>
        Your question was saved and is still being worked on. Answers usually arrive within a
        few seconds; this one is taking longer than expected.
      </p>
      <p className="mt-2">
        Reopen this conversation shortly to see it. Asking again will queue a second question
        rather than speed this one up. Meanwhile:
      </p>
      <div className="mt-2 flex flex-wrap gap-2">
        <Link
          href="/journal"
          className="inline-flex min-h-[44px] items-center gap-2 rounded-control border border-mist bg-card px-3 text-sm font-semibold"
        >
          <BookOpen aria-hidden className="size-4 text-forest" />
          Record what happened
        </Link>
        <Link
          href="/"
          className="inline-flex min-h-[44px] items-center gap-2 rounded-control border border-mist bg-card px-3 text-sm font-semibold"
        >
          <Sprout aria-hidden className="size-4 text-forest" />
          See your fields
        </Link>
      </div>
    </Callout>
  );
}
