"""HTTP interface registry. Status and request types are part of the frozen contract."""
from contracts.models import *

# method, path, request model, response data model, success code
ROUTES = [
    ('GET', '/me', None, Farmer, 200),
    ('PATCH', '/me', ProfilePatch, Farmer, 200),
    ('POST', '/me/export', None, Job, 202),
    ('DELETE', '/me', None, Job, 202),
    ('GET', '/fields', None, Page[Field], 200),
    ('POST', '/fields', FieldCreate, Field, 201),
    ('GET', '/fields/{id}', None, Field, 200),
    ('PATCH', '/fields/{id}', FieldPatch, Field, 200),
    ('POST', '/fields/{id}/archive', VersionedPatch, Field, 200),
    ('GET', '/fields/{id}/seasons', None, Page[Season], 200),
    ('POST', '/fields/{id}/seasons', SeasonCreate, Season, 201),
    ('GET', '/seasons/{id}', None, Season, 200),
    ('PATCH', '/seasons/{id}', SeasonPatch, Season, 200),
    ('POST', '/seasons/{id}/close', SeasonCloseRequest, SeasonEvaluation, 200),
    ('GET', '/seasons/{id}/summary', None, SeasonEvaluation, 200),
    ('POST', '/planning/compare', PlanningRequest, CropComparison, 200),
    ('POST', '/seasons/{id}/evaluate', EvaluateRequest, EvaluationBundle | Job, 200),
    ('GET', '/seasons/{id}/recommendations/latest', None, Recommendation, 200),
    ('GET', '/recommendations/{id}', None, Recommendation, 200),
    ('GET', '/seasons/{id}/forecast', None, ForecastBundle, 200),
    ('GET', '/seasons/{id}/water', None, WaterEstimate, 200),
    ('GET', '/seasons/{id}/economics', None, Economics, 200),
    ('GET', '/seasons/{id}/journal', None, Page[JournalEntry], 200),
    ('POST', '/seasons/{id}/journal', JournalCreate, JournalEntry, 201),
    ('PATCH', '/journal/{id}', JournalPatch, JournalEntry, 200),
    ('POST', '/media/uploads', UploadRequest, UploadTicket, 201),
    ('POST', '/media/{id}/complete', MediaComplete, MediaAsset, 200),
    ('GET', '/media/{id}/access', None, MediaAccess, 200),
    ('POST', '/soil/extractions', SoilExtractionRequest, Job, 202),
    ('GET', '/soil/extractions/{id}', None, SoilObservation, 200),
    ('POST', '/soil/extractions/{id}/confirm', SoilConfirmRequest, SoilObservation, 200),
    ('GET', '/tasks', None, Page[Task], 200),
    ('PATCH', '/tasks/{id}', TaskPatch, Task, 200),
    ('GET', '/notifications', None, Page[Notification], 200),
    ('PATCH', '/notifications/{id}', NotificationPatch, Notification, 200),
    ('GET', '/reminders', None, Page[Reminder], 200),
    ('POST', '/reminders', ReminderCreate, Reminder, 201),
    ('PATCH', '/reminders/{id}', ReminderPatch, Reminder, 200),
    ('DELETE', '/reminders/{id}', None, MutationReceipt, 200),
    ('POST', '/conversations', ConversationCreate, Conversation, 201),
    ('GET', '/conversations/{id}/messages', None, Page[Message], 200),
    ('POST', '/conversations/{id}/messages', MessageCreate, Message, 201),
    ('GET', '/proposals/{id}', None, ProposedMutation, 200),
    ('POST', '/proposals/{id}/confirm', VersionedPatch, MutationReceipt, 200),
    ('POST', '/proposals/{id}/cancel', VersionedPatch, MutationReceipt, 200),
    ('POST', '/channels/whatsapp/link', ChannelLinkRequest, ChannelLinkChallenge, 201),
    ('DELETE', '/channels/whatsapp/link', None, MutationReceipt, 200),
    ('POST', '/channels/push', PushRegistration, MutationReceipt, 201),
    ('DELETE', '/channels/push', PushUnregister, MutationReceipt, 200),
    ('GET', '/catalog/crops', None, Page[Crop], 200),
    ('GET', '/catalog/products', None, Page[Product], 200),
    ('GET', '/catalog/locations', None, Page[LocationResult], 200),
    ('GET', '/jobs/{id}', None, Job, 200),
    ('GET', '/agronomist/summary', None, AgronomistSummary, 200),
    ('GET', '/agronomist/fields', None, Page[Field], 200),
    ('GET', '/agronomist/stress-map', None, Page[StressMapPoint], 200),
    ('GET', '/agronomist/evidence', None, Page[EvidenceRecord], 200),
    ('POST', '/agronomist/backtests', BacktestRequest, Job, 202),
    ('GET', '/agronomist/models', None, Page[ModelVersion], 200),
]
