"""per subject rate limit windows

Revision ID: 688fcc5d7723
Revises: 7d0b0fa1bb6f
"""
from __future__ import annotations
from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa


revision: str = '688fcc5d7723'
down_revision: str | None = '7d0b0fa1bb6f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_windows',
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('bucket', sa.String(length=24), nullable=False),
    sa.Column('window_start', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('subject', 'bucket', 'window_start')
    )
    op.create_index('ix_rate_limit_window_start', 'rate_limit_windows', ['window_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rate_limit_window_start', table_name='rate_limit_windows')
    op.drop_table('rate_limit_windows')
    # ### end Alembic commands ###
