"""per consumer outbox delivery state

Revision ID: 7d0b0fa1bb6f
Revises: ba1423b0e662
"""
from __future__ import annotations
from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7d0b0fa1bb6f'
down_revision: str | None = 'ba1423b0e662'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumer_receipts', sa.Column('status', sa.String(length=24), nullable=False))
    op.add_column('consumer_receipts', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('consumer_receipts', sa.Column('available_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('consumer_receipts', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_consumer_receipts_available_at'), 'consumer_receipts', ['available_at'], unique=False)
    op.create_index(op.f('ix_consumer_receipts_status'), 'consumer_receipts', ['status'], unique=False)
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_column('outbox_events', 'status')
    op.drop_column('outbox_events', 'attempts')
    op.drop_column('outbox_events', 'lease_until')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('lease_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('outbox_events', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('outbox_events', sa.Column('status', sa.VARCHAR(length=24), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.drop_index(op.f('ix_consumer_receipts_status'), table_name='consumer_receipts')
    op.drop_index(op.f('ix_consumer_receipts_available_at'), table_name='consumer_receipts')
    op.alter_column('consumer_receipts', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('consumer_receipts', 'available_at')
    op.drop_column('consumer_receipts', 'attempts')
    op.drop_column('consumer_receipts', 'status')
    # ### end Alembic commands ###
