"""platform baseline

Revision ID: ba1423b0e662
Revises: 
"""
from __future__ import annotations
from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ba1423b0e662'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_status'), 'model_versions', ['status'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firebase_uid')
    )
    op.create_table('webhook_inbox',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_message_id', 'kind', name='uq_webhook_provider_event')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('farmers',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_farmer_tenant_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_farmers_tenant_id'), 'farmers', ['tenant_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('actor_id', 'operation', 'key')
    )
    op.create_table('memberships',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.CheckConstraint("role in ('farmer','agronomist','admin')", name='ck_membership_role'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id')
    )
    op.create_index(op.f('ix_memberships_tenant_id'), 'memberships', ['tenant_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_available_at'), 'outbox_events', ['available_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_events_tenant_id'), 'outbox_events', ['tenant_id'], unique=False)
    op.create_table('agronomist_assignments',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'farmer_id'], ['farmers.tenant_id', 'farmers.id'], name='fk_assignment_farmer'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'farmer_id')
    )
    op.create_index(op.f('ix_agronomist_assignments_tenant_id'), 'agronomist_assignments', ['tenant_id'], unique=False)
    op.create_table('channel_identities',
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('external_id_hash', sa.String(length=64), nullable=False),
    sa.Column('opted_in', sa.Boolean(), nullable=False),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id_hash', name='uq_channel_identity')
    )
    op.create_index(op.f('ix_channel_identities_farmer_id'), 'channel_identities', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_channel_identities_tenant_id'), 'channel_identities', ['tenant_id'], unique=False)
    op.create_table('channel_link_challenges',
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_index(op.f('ix_channel_link_challenges_farmer_id'), 'channel_link_challenges', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_channel_link_challenges_tenant_id'), 'channel_link_challenges', ['tenant_id'], unique=False)
    op.create_table('consumer_receipts',
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('consumer', sa.String(length=128), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['outbox_events.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'consumer')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_conversation_tenant_id')
    )
    op.create_index(op.f('ix_conversations_farmer_id'), 'conversations', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_table('fields',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('area_ha > 0', name='ck_field_area'),
    sa.ForeignKeyConstraint(['tenant_id', 'farmer_id'], ['farmers.tenant_id', 'farmers.id'], name='fk_field_farmer'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_field_tenant_id')
    )
    op.create_index(op.f('ix_fields_farmer_id'), 'fields', ['farmer_id'], unique=False)
    op.create_index('ix_fields_owner_page', 'fields', ['tenant_id', 'farmer_id', 'id'], unique=False)
    op.create_index(op.f('ix_fields_tenant_id'), 'fields', ['tenant_id'], unique=False)
    op.create_table('jobs',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_token', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_farmer_id'), 'jobs', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_jobs_run_after'), 'jobs', ['run_after'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('object_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_media_assets_farmer_id'), 'media_assets', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_media_assets_tenant_id'), 'media_assets', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'conversation_id'], ['conversations.tenant_id', 'conversations.id'], name='fk_message_conversation'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_farmer_id'), 'messages', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_table('proposed_mutations',
    sa.Column('conversation_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'conversation_id'], ['conversations.tenant_id', 'conversations.id'], name='fk_proposal_conversation'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposed_mutations_conversation_id'), 'proposed_mutations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_proposed_mutations_farmer_id'), 'proposed_mutations', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_proposed_mutations_tenant_id'), 'proposed_mutations', ['tenant_id'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('field_id', sa.String(length=128), nullable=False),
    sa.Column('crop_id', sa.String(length=128), nullable=False),
    sa.Column('allocated_area_ha', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint("status in ('planned','active','closed')", name='ck_season_status'),
    sa.CheckConstraint('allocated_area_ha > 0', name='ck_season_area'),
    sa.ForeignKeyConstraint(['tenant_id', 'field_id'], ['fields.tenant_id', 'fields.id'], name='fk_season_field'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_season_tenant_id')
    )
    op.create_index(op.f('ix_seasons_field_id'), 'seasons', ['field_id'], unique=False)
    op.create_index('ix_seasons_field_page', 'seasons', ['tenant_id', 'field_id', 'id'], unique=False)
    op.create_index(op.f('ix_seasons_tenant_id'), 'seasons', ['tenant_id'], unique=False)
    op.create_table('soil_observations',
    sa.Column('field_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'field_id'], ['fields.tenant_id', 'fields.id'], name='fk_soil_field'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil_observations_farmer_id'), 'soil_observations', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_soil_observations_field_id'), 'soil_observations', ['field_id'], unique=False)
    op.create_index(op.f('ix_soil_observations_tenant_id'), 'soil_observations', ['tenant_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('season_id', sa.String(length=128), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'farmer_id'], ['farmers.tenant_id', 'farmers.id'], name='fk_journal_farmer'),
    sa.ForeignKeyConstraint(['tenant_id', 'season_id'], ['seasons.tenant_id', 'seasons.id'], name='fk_journal_season'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_journal_tenant_id')
    )
    op.create_index(op.f('ix_journal_entries_farmer_id'), 'journal_entries', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_season_id'), 'journal_entries', ['season_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_tenant_id'), 'journal_entries', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('season_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'season_id'], ['seasons.tenant_id', 'seasons.id'], name='fk_notification_season'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_farmer_id'), 'notifications', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_notifications_season_id'), 'notifications', ['season_id'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('season_id', sa.String(length=128), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_version', sa.Integer(), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'season_id'], ['seasons.tenant_id', 'seasons.id'], name='fk_recommendation_season'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'input_hash', name='uq_recommendation_snapshot')
    )
    op.create_index(op.f('ix_recommendations_farmer_id'), 'recommendations', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_recommendations_season_id'), 'recommendations', ['season_id'], unique=False)
    op.create_index(op.f('ix_recommendations_tenant_id'), 'recommendations', ['tenant_id'], unique=False)
    op.create_table('reminders',
    sa.Column('season_id', sa.String(length=128), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'season_id'], ['seasons.tenant_id', 'seasons.id'], name='fk_reminder_season'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_farmer_id'), 'reminders', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_reminders_scheduled_at'), 'reminders', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_reminders_season_id'), 'reminders', ['season_id'], unique=False)
    op.create_index(op.f('ix_reminders_status'), 'reminders', ['status'], unique=False)
    op.create_index(op.f('ix_reminders_tenant_id'), 'reminders', ['tenant_id'], unique=False)
    op.create_table('season_closures',
    sa.Column('season_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'season_id'], ['seasons.tenant_id', 'seasons.id'], name='fk_closure_season'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id')
    )
    op.create_index(op.f('ix_season_closures_farmer_id'), 'season_closures', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_season_closures_tenant_id'), 'season_closures', ['tenant_id'], unique=False)
    op.create_table('tasks',
    sa.Column('season_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deduplication_key', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'season_id'], ['seasons.tenant_id', 'seasons.id'], name='fk_task_season'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'deduplication_key', name='uq_task_deduplication')
    )
    op.create_index(op.f('ix_tasks_due_at'), 'tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_tasks_farmer_id'), 'tasks', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_tasks_season_id'), 'tasks', ['season_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_table('economic_ledger_lines',
    sa.Column('season_id', sa.String(length=128), nullable=False),
    sa.Column('journal_entry_id', sa.String(length=128), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('farmer_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_ledger_amount'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'journal_entry_id'], ['journal_entries.tenant_id', 'journal_entries.id'], name='fk_ledger_journal'),
    sa.ForeignKeyConstraint(['tenant_id', 'season_id'], ['seasons.tenant_id', 'seasons.id'], name='fk_ledger_season'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_ledger_lines_farmer_id'), 'economic_ledger_lines', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_economic_ledger_lines_journal_entry_id'), 'economic_ledger_lines', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_economic_ledger_lines_season_id'), 'economic_ledger_lines', ['season_id'], unique=False)
    op.create_index(op.f('ix_economic_ledger_lines_tenant_id'), 'economic_ledger_lines', ['tenant_id'], unique=False)
    op.create_table('journal_revisions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('journal_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id', 'version', name='uq_journal_revision')
    )
    op.create_index(op.f('ix_journal_revisions_journal_id'), 'journal_revisions', ['journal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_revisions_journal_id'), table_name='journal_revisions')
    op.drop_table('journal_revisions')
    op.drop_index(op.f('ix_economic_ledger_lines_tenant_id'), table_name='economic_ledger_lines')
    op.drop_index(op.f('ix_economic_ledger_lines_season_id'), table_name='economic_ledger_lines')
    op.drop_index(op.f('ix_economic_ledger_lines_journal_entry_id'), table_name='economic_ledger_lines')
    op.drop_index(op.f('ix_economic_ledger_lines_farmer_id'), table_name='economic_ledger_lines')
    op.drop_table('economic_ledger_lines')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_season_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_farmer_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_season_closures_tenant_id'), table_name='season_closures')
    op.drop_index(op.f('ix_season_closures_farmer_id'), table_name='season_closures')
    op.drop_table('season_closures')
    op.drop_index(op.f('ix_reminders_tenant_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_status'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_season_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_scheduled_at'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_farmer_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_recommendations_tenant_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_season_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_farmer_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_season_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_farmer_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_journal_entries_tenant_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_season_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_farmer_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_soil_observations_tenant_id'), table_name='soil_observations')
    op.drop_index(op.f('ix_soil_observations_field_id'), table_name='soil_observations')
    op.drop_index(op.f('ix_soil_observations_farmer_id'), table_name='soil_observations')
    op.drop_table('soil_observations')
    op.drop_index(op.f('ix_seasons_tenant_id'), table_name='seasons')
    op.drop_index('ix_seasons_field_page', table_name='seasons')
    op.drop_index(op.f('ix_seasons_field_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_proposed_mutations_tenant_id'), table_name='proposed_mutations')
    op.drop_index(op.f('ix_proposed_mutations_farmer_id'), table_name='proposed_mutations')
    op.drop_index(op.f('ix_proposed_mutations_conversation_id'), table_name='proposed_mutations')
    op.drop_table('proposed_mutations')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_farmer_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_media_assets_tenant_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_farmer_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_run_after'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_farmer_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_fields_tenant_id'), table_name='fields')
    op.drop_index('ix_fields_owner_page', table_name='fields')
    op.drop_index(op.f('ix_fields_farmer_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_farmer_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('consumer_receipts')
    op.drop_index(op.f('ix_channel_link_challenges_tenant_id'), table_name='channel_link_challenges')
    op.drop_index(op.f('ix_channel_link_challenges_farmer_id'), table_name='channel_link_challenges')
    op.drop_table('channel_link_challenges')
    op.drop_index(op.f('ix_channel_identities_tenant_id'), table_name='channel_identities')
    op.drop_index(op.f('ix_channel_identities_farmer_id'), table_name='channel_identities')
    op.drop_table('channel_identities')
    op.drop_index(op.f('ix_agronomist_assignments_tenant_id'), table_name='agronomist_assignments')
    op.drop_table('agronomist_assignments')
    op.drop_index(op.f('ix_outbox_events_tenant_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_available_at'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_memberships_tenant_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_farmers_tenant_id'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('webhook_inbox')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_model_versions_status'), table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
